/**
 * @fileoverview
 * @enhanceable
 * @suppress {messageConventions} JS Compiler reports an error if a variable or
 *     field starts with 'MSG_' and isn't a translatable message.
 * @public
 */
// GENERATED CODE -- DO NOT EDIT!

goog.provide('proto.game.net_msg');

goog.require('jspb.BinaryReader');
goog.require('jspb.BinaryWriter');
goog.require('jspb.Message');


/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.game.net_msg = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.game.net_msg, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  proto.game.net_msg.displayName = 'proto.game.net_msg';
}


if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto suitable for use in Soy templates.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     com.google.apps.jspb.JsClassTemplate.JS_RESERVED_WORDS.
 * @param {boolean=} opt_includeInstance Whether to include the JSPB instance
 *     for transitional soy proto support: http://goto/soy-param-migration
 * @return {!Object}
 */
proto.game.net_msg.prototype.toObject = function(opt_includeInstance) {
  return proto.game.net_msg.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Whether to include the JSPB
 *     instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.game.net_msg} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.game.net_msg.toObject = function(includeInstance, msg) {
  var f, obj = {
    v: jspb.Message.getFieldWithDefault(msg, 1, 0),
    mId: jspb.Message.getFieldWithDefault(msg, 2, 0),
    sId: jspb.Message.getFieldWithDefault(msg, 3, 0),
    opt: jspb.Message.getFieldWithDefault(msg, 4, 0),
    data: jspb.Message.getFieldWithDefault(msg, 5, "")
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.game.net_msg}
 */
proto.game.net_msg.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.game.net_msg;
  return proto.game.net_msg.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.game.net_msg} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.game.net_msg}
 */
proto.game.net_msg.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {number} */ (reader.readInt32());
      msg.setV(value);
      break;
    case 2:
      var value = /** @type {number} */ (reader.readInt32());
      msg.setMId(value);
      break;
    case 3:
      var value = /** @type {number} */ (reader.readInt32());
      msg.setSId(value);
      break;
    case 4:
      var value = /** @type {number} */ (reader.readInt32());
      msg.setOpt(value);
      break;
    case 5:
      var value = /** @type {string} */ (reader.readString());
      msg.setData(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.game.net_msg.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.game.net_msg.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.game.net_msg} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.game.net_msg.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getV();
  if (f !== 0) {
    writer.writeInt32(
      1,
      f
    );
  }
  f = message.getMId();
  if (f !== 0) {
    writer.writeInt32(
      2,
      f
    );
  }
  f = message.getSId();
  if (f !== 0) {
    writer.writeInt32(
      3,
      f
    );
  }
  f = message.getOpt();
  if (f !== 0) {
    writer.writeInt32(
      4,
      f
    );
  }
  f = message.getData();
  if (f.length > 0) {
    writer.writeString(
      5,
      f
    );
  }
};


/**
 * optional int32 v = 1;
 * @return {number}
 */
proto.game.net_msg.prototype.getV = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 1, 0));
};


/** @param {number} value */
proto.game.net_msg.prototype.setV = function(value) {
  jspb.Message.setProto3IntField(this, 1, value);
};


/**
 * optional int32 m_id = 2;
 * @return {number}
 */
proto.game.net_msg.prototype.getMId = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 2, 0));
};


/** @param {number} value */
proto.game.net_msg.prototype.setMId = function(value) {
  jspb.Message.setProto3IntField(this, 2, value);
};


/**
 * optional int32 s_id = 3;
 * @return {number}
 */
proto.game.net_msg.prototype.getSId = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 3, 0));
};


/** @param {number} value */
proto.game.net_msg.prototype.setSId = function(value) {
  jspb.Message.setProto3IntField(this, 3, value);
};


/**
 * optional int32 opt = 4;
 * @return {number}
 */
proto.game.net_msg.prototype.getOpt = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 4, 0));
};


/** @param {number} value */
proto.game.net_msg.prototype.setOpt = function(value) {
  jspb.Message.setProto3IntField(this, 4, value);
};


/**
 * optional string data = 5;
 * @return {string}
 */
proto.game.net_msg.prototype.getData = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 5, ""));
};


/** @param {string} value */
proto.game.net_msg.prototype.setData = function(value) {
  jspb.Message.setProto3StringField(this, 5, value);
};


